services:
  - type: web
    name: dev-web-ing1-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /api/health

  - type: web
    name: dev-web-ing1-web
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_BASE_URL
        value: https://dev-web-ing1-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
