services:
  - type: web
    name: dev-web-ing1-api
    env: java
    plan: free
    buildCommand: mvn -DskipTests clean package
    startCommand: java -Dserver.port=$PORT -jar target/projet-1.0-SNAPSHOT.jar
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: JAVA_VERSION
        value: 21

  - type: web
    name: dev-web-ing1-web
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_BASE_URL
        value: https://dev-web-ing1-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
