spring.datasource.url=${APP_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3307/maison_intelligente?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${APP_DATASOURCE_USERNAME:maison}
spring.datasource.password=${APP_DATASOURCE_PASSWORD:maison123}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
